package com.einsteindash.backend.util;

import com.einsteindash.backend.model.Level;
import com.einsteindash.backend.repository.LevelRepository;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class DataSeeder {

    @Bean
    CommandLineRunner initDatabase(LevelRepository repository) {
        return args -> {
            if (true) {
                Level l1 = repository.findByLevelName("Stereo Madness").orElse(new Level());
                l1.setLevelName("Stereo Madness");
                l1.setLevelData("""
                            [
                             {"type": "SPIKE", "x": 18, "y": 0},
    
                             {"type": "SPIKE", "x": 38, "y": 0},
                             {"type": "SPIKE", "x": 39, "y": 0},
    
                             {"type": "SPIKE", "x": 65, "y": 0},
    
                             {"type": "SPIKE", "x": 72, "y": 0},
                             {"type": "SPIKE", "x": 73, "y": 0},
    
                             {"type": "SPIKE", "x": 90, "y": 0},
    
                             {"type": "SPIKE", "x": 108, "y": 0},
                             {"type": "SPIKE", "x": 109, "y": 0},
                             {"type": "SPIKE", "x": 110 , "y": 0},
    
                             {"type": "SPIKE", "x": 135, "y": 0},
    
                             {"type": "PORTAL_SPEED_2", "x": 142, "y": 0},
                             {"type": "PORTAL_SHIP", "x": 143, "y": 0},
    
                             {"type": "SPIKE", "x": 151, "y": 0},
                             {"type": "SPIKE", "x": 152, "y": 0},
                             {"type": "SPIKE", "x": 153, "y": 0},
                             {"type": "SPIKE", "x": 154, "y": 0},
                             {"type": "SPIKE", "x": 155, "y": 0},
                             {"type": "SPIKE", "x": 156, "y": 0},
                             {"type": "SPIKE", "x": 157, "y": 0},
                             {"type": "SPIKE", "x": 158, "y": 0},
                             {"type": "SPIKE", "x": 159, "y": 0},
                             {"type": "SPIKE", "x": 160, "y": 0},
                             {"type": "SPIKE", "x": 161, "y": 0},
                             {"type": "SPIKE", "x": 162, "y": 0},
                             {"type": "SPIKE", "x": 163, "y": 0},
                             {"type": "SPIKE", "x": 164, "y": 0},
                             {"type": "SPIKE", "x": 165, "y": 0},
                             {"type": "SPIKE", "x": 166, "y": 0},
                             {"type": "SPIKE", "x": 167, "y": 0},
                             {"type": "SPIKE", "x": 168, "y": 0},
                             {"type": "SPIKE", "x": 169, "y": 0},
                             {"type": "SPIKE", "x": 170, "y": 0},
                             {"type": "SPIKE", "x": 171, "y": 0},
                             {"type": "SPIKE", "x": 172, "y": 0},
                             {"type": "SPIKE", "x": 173, "y": 0},
                             {"type": "SPIKE", "x": 174, "y": 0},
                             {"type": "SPIKE", "x": 175, "y": 0},
                             {"type": "SPIKE", "x": 176, "y": 0},
                             {"type": "SPIKE", "x": 177, "y": 0},
                             {"type": "SPIKE", "x": 178, "y": 0},
                             {"type": "SPIKE", "x": 179, "y": 0},
                             {"type": "SPIKE", "x": 180, "y": 0},
                             {"type": "SPIKE", "x": 181, "y": 0},
                             {"type": "SPIKE", "x": 182, "y": 0},
                             {"type": "SPIKE", "x": 183, "y": 0},
                             {"type": "SPIKE", "x": 184, "y": 0},
                             {"type": "SPIKE", "x": 185, "y": 0},
                             {"type": "SPIKE", "x": 186, "y": 0},
                             {"type": "SPIKE", "x": 187, "y": 0},
                             {"type": "SPIKE", "x": 188, "y": 0},
                             {"type": "SPIKE", "x": 189, "y": 0},
                             {"type": "SPIKE", "x": 190, "y": 0},
                             {"type": "SPIKE", "x": 191, "y": 0},
                             {"type": "SPIKE", "x": 192, "y": 0},
                             {"type": "SPIKE", "x": 193, "y": 0},
                             {"type": "SPIKE", "x": 194, "y": 0},
                             {"type": "SPIKE", "x": 195, "y": 0},
                             {"type": "SPIKE", "x": 196, "y": 0},
                             {"type": "SPIKE", "x": 197, "y": 0},
                             {"type": "SPIKE", "x": 198, "y": 0},
                             {"type": "SPIKE", "x": 199, "y": 0},
                             {"type": "SPIKE", "x": 200, "y": 0},
                             {"type": "SPIKE", "x": 201, "y": 0},
                             {"type": "SPIKE", "x": 202, "y": 0},
                             {"type": "SPIKE", "x": 203, "y": 0},
                             {"type": "SPIKE", "x": 204, "y": 0},
                             {"type": "SPIKE", "x": 205, "y": 0},
                             {"type": "SPIKE", "x": 206, "y": 0},
                             {"type": "SPIKE", "x": 207, "y": 0},
                             {"type": "SPIKE", "x": 208, "y": 0},
                             {"type": "SPIKE", "x": 209, "y": 0},
                             {"type": "SPIKE", "x": 210, "y": 0},
                             {"type": "SPIKE", "x": 211, "y": 0},
                             {"type": "SPIKE", "x": 212, "y": 0},
                             {"type": "SPIKE", "x": 213, "y": 0},
                             {"type": "SPIKE", "x": 214, "y": 0},
                             {"type": "SPIKE", "x": 215, "y": 0},
                             {"type": "SPIKE", "x": 216, "y": 0},
                             {"type": "SPIKE", "x": 217, "y": 0},
                             {"type": "SPIKE", "x": 218, "y": 0},
                             {"type": "SPIKE", "x": 219, "y": 0},
                             {"type": "SPIKE", "x": 220, "y": 0},
                             {"type": "SPIKE", "x": 221, "y": 0},
                             {"type": "SPIKE", "x": 222, "y": 0},
                             {"type": "SPIKE", "x": 223, "y": 0},
                             {"type": "SPIKE", "x": 224, "y": 0},
                             {"type": "SPIKE", "x": 225, "y": 0},
                             {"type": "SPIKE", "x": 226, "y": 0},
                             {"type": "SPIKE", "x": 227, "y": 0},
                             {"type": "SPIKE", "x": 228, "y": 0},
                             {"type": "SPIKE", "x": 229, "y": 0},
                             {"type": "SPIKE", "x": 230, "y": 0},
    
    
                             {"type": "SPIKE_UPSIDE", "x": 151, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 152, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 153, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 154, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 155, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 156, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 157, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 158, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 159, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 160, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 161, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 162, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 163, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 164, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 165, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 166, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 167, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 168, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 169, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 170, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 171, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 172, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 173, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 174, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 175, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 176, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 177, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 178, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 179, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 180, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 181, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 182, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 183, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 184, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 185, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 186, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 187, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 188, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 189, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 190, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 191, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 192, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 193, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 194, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 195, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 196, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 197, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 198, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 199, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 200, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 201, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 202, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 203, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 204, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 205, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 206, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 207, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 208, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 209, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 210, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 211, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 212, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 213, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 214, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 215, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 216, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 217, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 218, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 219, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 220, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 221, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 222, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 223, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 224, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 225, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 226, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 227, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 228, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 229, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 230, "y": 6},
    
                             {"type": "BLOCK", "x": 161, "y": 2},
                             {"type": "BLOCK", "x": 175, "y": 4},
                             {"type": "BLOCK", "x": 183, "y": 2},
    
                             {"type": "PORTAL_UFO", "x": 183, "y": 3},
    
                             {"type": "BLOCK", "x": 231, "y": 6},
                             {"type": "BLOCK", "x": 231, "y": 5},
                             {"type": "PORTAL_ROBOT", "x": 231, "y": 2},
                             {"type": "PORTAL_SPEED_1", "x": 232, "y": 2},
                             {"type": "BLOCK", "x": 231, "y": 0},
    
    
                             {"type": "SPIKE", "x": 240, "y": 0},
                             {"type": "SPIKE", "x": 241, "y": 0},
                             {"type": "SPIKE", "x": 242, "y": 0},
    
                             {"type": "BLOCK", "x": 255, "y": 0},
                             {"type": "BLOCK", "x": 256, "y": 0},
                             {"type": "BLOCK", "x": 257, "y": 0},
                             {"type": "BLOCK", "x": 258, "y": 0},
                             {"type": "BLOCK", "x": 259, "y": 0},
                             {"type": "BLOCK", "x": 260, "y": 0},
                             {"type": "BLOCK", "x": 261, "y": 0},
                             {"type": "BLOCK", "x": 262, "y": 0}, {"type": "BLOCK", "x": 262, "y": 1}, {"type": "BLOCK", "x": 262, "y": 2},
                             {"type": "BLOCK", "x": 263, "y": 2}, {"type": "BLOCK", "x": 263, "y": 1}, {"type": "BLOCK", "x": 263, "y": 0},
    
    
                             {"type": "PORTAL_BALL", "x": 295, "y": 0},
    
    
                             {"type": "SPIKE", "x": 305, "y": 0},
                             {"type": "SPIKE", "x": 306, "y": 0},
                             {"type": "SPIKE", "x": 307, "y": 0},
                             {"type": "SPIKE", "x": 308, "y": 0},
                             {"type": "SPIKE", "x": 309, "y": 0},
                             {"type": "SPIKE", "x": 310, "y": 0},
    
                             {"type": "SPIKE_UPSIDE", "x": 311, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 312, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 313, "y": 6},
    
                             {"type": "BLOCK", "x": 311, "y": 1}, {"type": "BLOCK", "x": 311, "y": 0},
                             {"type": "BLOCK", "x": 312, "y": 1},
                             {"type": "BLOCK", "x": 313, "y": 1},
                             {"type": "BLOCK", "x": 314, "y": 1}, {"type": "SPIKE", "x": 314, "y": 2}, {"type": "BLOCK", "x": 314, "y": 0},
    
                             {"type": "SPIKE", "x": 315, "y": 0},
                             {"type": "SPIKE", "x": 316, "y": 0},
                             {"type": "SPIKE", "x": 317, "y": 0},
                             {"type": "SPIKE", "x": 318, "y": 0},
                             {"type": "SPIKE", "x": 319, "y": 0},
                             {"type": "SPIKE", "x": 320, "y": 0},
                             {"type": "SPIKE", "x": 321, "y": 0},
                             {"type": "SPIKE", "x": 322, "y": 0},
                             {"type": "SPIKE", "x": 323, "y": 0},
    
                             {"type": "SPIKE_UPSIDE", "x": 325, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 326, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 327, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 328, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 329, "y": 6},
    
                             {"type": "PORTAL_SPIDER", "x": 330, "y": 0},
    
                             {"type": "SPIKE", "x": 341, "y": 0},
                             {"type": "SPIKE", "x": 342, "y": 0},
                             {"type": "SPIKE", "x": 343, "y": 0},
                             {"type": "SPIKE", "x": 344, "y": 0},
                             {"type": "SPIKE", "x": 345, "y": 0},
    
                             {"type": "SPIKE_UPSIDE", "x": 350, "y": 6},
    
                             {"type": "SPIKE", "x": 355, "y": 0},
    
                             {"type": "SPIKE_UPSIDE", "x": 360, "y": 6},
    
                             {"type": "SPIKE", "x": 365, "y": 0},
    
                             {"type": "SPIKE_UPSIDE", "x": 370, "y": 6},
    
                             {"type": "PORTAL_ROBOT", "x": 375, "y": 0},
                             {"type": "PORTAL_GRAVITY_UP", "x": 376, "y": 0},
    
    
                             {"type": "SPIKE_UPSIDE", "x": 385, "y": 6},
    
                             {"type": "SPIKE_UPSIDE", "x": 390, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 391, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 392, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 393, "y": 6},
    
                             {"type": "SPIKE_UPSIDE", "x": 398, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 399, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 400, "y": 6},
    
                             {"type": "PORTAL_GRAVITY_DOWN", "x": 410, "y": 5},
    
    
                             {"type": "SPIKE_UPSIDE", "x": 415, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 416, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 417, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 418, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 419, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 420, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 421, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 422, "y": 6},
                             {"type": "SPIKE_UPSIDE", "x": 423, "y": 6},
    
                             {"type": "SPIKE", "x": 420, "y": 0},
                             {"type": "SPIKE", "x": 421, "y": 0},
                             {"type": "SPIKE", "x": 422, "y": 0},
    
                             {"type": "SPIKE", "x": 430, "y": 0},
                             {"type": "SPIKE", "x": 431, "y": 0},
                             {"type": "SPIKE", "x": 432, "y": 0},
                             {"type": "SPIKE", "x": 433, "y": 0},
    
                             {"type": "PORTAL_WAVE", "x": 433, "y": 1},
    
                             {"type": "BLOCK", "x": 440, "y": 0}, {"type": "BLOCK", "x": 440, "y": 1}, {"type": "BLOCK", "x": 440, "y": 2},
                             {"type": "BLOCK", "x": 440, "y": 3}, {"type": "BLOCK", "x": 440, "y": 4}, {"type": "BLOCK", "x": 440, "y": 5},
                             {"type": "BLOCK", "x": 441, "y": 5},
                             {"type": "BLOCK", "x": 442, "y": 5},
                             {"type": "BLOCK", "x": 443, "y": 5},
                             {"type": "BLOCK", "x": 444, "y": 5}, {"type": "BLOCK", "x": 444, "y": 1}, {"type": "BLOCK", "x": 444, "y": 2},
                             {"type": "BLOCK", "x": 444, "y": 3}, {"type": "BLOCK", "x": 444, "y": 4}, {"type": "BLOCK", "x": 444, "y": 0},
    
                             {"type": "BLOCK", "x": 450, "y": 0}, {"type": "BLOCK", "x": 450, "y": 1},
                             {"type": "BLOCK", "x": 451, "y": 1},
                             {"type": "BLOCK", "x": 452, "y": 1},
                             {"type": "BLOCK", "x": 453, "y": 1},
                             {"type": "BLOCK", "x": 454, "y": 1}, {"type": "BLOCK", "x": 450, "y": 0},
    
                             {"type": "BLOCK", "x": 450, "y": 6}, {"type": "BLOCK", "x": 450, "y": 5},
                             {"type": "BLOCK", "x": 451, "y": 5},
                             {"type": "BLOCK", "x": 452, "y": 5},
                             {"type": "BLOCK", "x": 453, "y": 5},
                             {"type": "BLOCK", "x": 454, "y": 5}, {"type": "BLOCK", "x": 454, "y": 6},
    
                             {"type": "BLOCK", "x": 457, "y": 0}, {"type": "BLOCK", "x": 457, "y": 1}, {"type": "BLOCK", "x": 457, "y": 2},
                             {"type": "BLOCK", "x": 457, "y": 3},
    
                             {"type": "BLOCK", "x": 460, "y": 0}, {"type": "BLOCK", "x": 460, "y": 1},
                             {"type": "BLOCK", "x": 461, "y": 1},
                             {"type": "BLOCK", "x": 462, "y": 1},
                             {"type": "BLOCK", "x": 463, "y": 1},
                             {"type": "BLOCK", "x": 464, "y": 1},
                             {"type": "BLOCK", "x": 465, "y": 1},
                             {"type": "BLOCK", "x": 466, "y": 1},
                             {"type": "BLOCK", "x": 467, "y": 1},
                             {"type": "BLOCK", "x": 468, "y": 1},
                             {"type": "BLOCK", "x": 469, "y": 1},
                             {"type": "BLOCK", "x": 470, "y": 1}, {"type": "BLOCK", "x": 470, "y": 0},
    
                             {"type": "BLOCK", "x": 460, "y": 6}, {"type": "BLOCK", "x": 460, "y": 5},
                             {"type": "BLOCK", "x": 461, "y": 5},
                             {"type": "BLOCK", "x": 462, "y": 5},
                             {"type": "BLOCK", "x": 463, "y": 5},
                             {"type": "BLOCK", "x": 464, "y": 5},
                             {"type": "BLOCK", "x": 465, "y": 5},
                             {"type": "BLOCK", "x": 466, "y": 5},
                             {"type": "BLOCK", "x": 467, "y": 5},
                             {"type": "BLOCK", "x": 468, "y": 5},
                             {"type": "BLOCK", "x": 469, "y": 5},
                             {"type": "BLOCK", "x": 470, "y": 5}, {"type": "BLOCK", "x": 470, "y": 6},
    
                             {"type": "BLOCK", "x": 475, "y": 0}, {"type": "BLOCK", "x": 475, "y": 1}, {"type": "BLOCK", "x": 475, "y": 2},
                             {"type": "BLOCK", "x": 475, "y": 3}, {"type": "BLOCK", "x": 475, "y": 4}, {"type": "BLOCK", "x": 475, "y": 5},
                             {"type": "BLOCK", "x": 476, "y": 5},
                             {"type": "BLOCK", "x": 477, "y": 5},
                             {"type": "BLOCK", "x": 478, "y": 5},
                             {"type": "BLOCK", "x": 479, "y": 5}, {"type": "BLOCK", "x": 479, "y": 1}, {"type": "BLOCK", "x": 479, "y": 2},
                             {"type": "BLOCK", "x": 479, "y": 3}, {"type": "BLOCK", "x": 479, "y": 4}, {"type": "BLOCK", "x": 479, "y": 0},
    
                             {"type": "SPIKE", "x": 480, "y": 0},
                             {"type": "SPIKE", "x": 480, "y": 0},
                             {"type": "SPIKE", "x": 481, "y": 0},
                             {"type": "SPIKE", "x": 482, "y": 0},
                             {"type": "SPIKE", "x": 483, "y": 0},
                             {"type": "SPIKE", "x": 484, "y": 0},
                             {"type": "SPIKE", "x": 485, "y": 0},
                             {"type": "SPIKE", "x": 486, "y": 0},
                             {"type": "SPIKE", "x": 487, "y": 0},
                             {"type": "SPIKE", "x": 488, "y": 0},
                             {"type": "SPIKE", "x": 489, "y": 0},
                             {"type": "SPIKE", "x": 490, "y": 0},
                             {"type": "SPIKE", "x": 491, "y": 0},
                             {"type": "SPIKE", "x": 492, "y": 0},
                             {"type": "SPIKE", "x": 493, "y": 0},
                             {"type": "SPIKE", "x": 494, "y": 0},
                             {"type": "SPIKE", "x": 495, "y": 0},
                             {"type": "SPIKE", "x": 496, "y": 0},
                             {"type": "SPIKE", "x": 497, "y": 0},
                             {"type": "SPIKE", "x": 498, "y": 0},
                             {"type": "SPIKE", "x": 499, "y": 0},
                             {"type": "SPIKE", "x": 500, "y": 0},
                             {"type": "SPIKE", "x": 501, "y": 0},
                             {"type": "SPIKE", "x": 502, "y": 0},
                             {"type": "SPIKE", "x": 503, "y": 0},
                             {"type": "SPIKE", "x": 504, "y": 0},
                             {"type": "SPIKE", "x": 505, "y": 0},
                             {"type": "SPIKE", "x": 506, "y": 0},
                             {"type": "SPIKE", "x": 507, "y": 0},
                             {"type": "SPIKE", "x": 508, "y": 0},
                             {"type": "SPIKE", "x": 509, "y": 0},
                             {"type": "SPIKE", "x": 510, "y": 0},
                             {"type": "SPIKE", "x": 511, "y": 0},
                             {"type": "SPIKE", "x": 512, "y": 0},
                             {"type": "SPIKE", "x": 513, "y": 0},
                             {"type": "SPIKE", "x": 514, "y": 0},
                             {"type": "SPIKE", "x": 515, "y": 0},
                             {"type": "SPIKE", "x": 516, "y": 0},
                             {"type": "SPIKE", "x": 517, "y": 0},
                             {"type": "SPIKE", "x": 518, "y": 0},
                             {"type": "SPIKE", "x": 519, "y": 0},
                             {"type": "SPIKE", "x": 520, "y": 0},
                             {"type": "SPIKE", "x": 521, "y": 0},
                             {"type": "SPIKE", "x": 522, "y": 0},
                             {"type": "SPIKE", "x": 523, "y": 0},
                             {"type": "SPIKE", "x": 524, "y": 0},
                             {"type": "SPIKE", "x": 525, "y": 0},
                             {"type": "SPIKE", "x": 526, "y": 0},
                             {"type": "SPIKE", "x": 527, "y": 0},
                             {"type": "SPIKE", "x": 528, "y": 0},
                             {"type": "SPIKE", "x": 529, "y": 0},
                             {"type": "SPIKE", "x": 530, "y": 0},
                             {"type": "SPIKE", "x": 531, "y": 0},
                             {"type": "SPIKE", "x": 532, "y": 0},
                             {"type": "SPIKE", "x": 533, "y": 0},
                             {"type": "SPIKE", "x": 534, "y": 0},
                             {"type": "SPIKE", "x": 535, "y": 0},
                             {"type": "SPIKE", "x": 536, "y": 0},
                             {"type": "SPIKE", "x": 537, "y": 0},
                             {"type": "SPIKE", "x": 538, "y": 0},
                             {"type": "SPIKE", "x": 539, "y": 0},
                             {"type": "SPIKE", "x": 540, "y": 0},
                             {"type": "SPIKE", "x": 541, "y": 0},
                             {"type": "SPIKE", "x": 542, "y": 0},
                             {"type": "SPIKE", "x": 543, "y": 0},
                             {"type": "SPIKE", "x": 544, "y": 0},
                             {"type": "SPIKE", "x": 545, "y": 0},
                             {"type": "SPIKE", "x": 546, "y": 0},
                             {"type": "SPIKE", "x": 547, "y": 0},
                             {"type": "SPIKE", "x": 548, "y": 0},
                             {"type": "SPIKE", "x": 549, "y": 0},
                             {"type": "SPIKE", "x": 550, "y": 0},
                             {"type": "SPIKE", "x": 551, "y": 0},
                             {"type": "SPIKE", "x": 552, "y": 0},
                             {"type": "SPIKE", "x": 553, "y": 0},
                             {"type": "SPIKE", "x": 554, "y": 0},
                             {"type": "SPIKE", "x": 555, "y": 0},
                             {"type": "SPIKE", "x": 556, "y": 0},
                             {"type": "SPIKE", "x": 557, "y": 0},
                             {"type": "SPIKE", "x": 558, "y": 0},
                             {"type": "SPIKE", "x": 559, "y": 0},
                             {"type": "SPIKE", "x": 560, "y": 0},
                             {"type": "SPIKE", "x": 561, "y": 0},
                             {"type": "SPIKE", "x": 562, "y": 0},
                             {"type": "SPIKE", "x": 563, "y": 0},
                             {"type": "SPIKE", "x": 564, "y": 0},
                             {"type": "SPIKE", "x": 565, "y": 0},
                             {"type": "SPIKE", "x": 566, "y": 0},
                             {"type": "SPIKE", "x": 567, "y": 0},
                             {"type": "SPIKE", "x": 568, "y": 0},
                             {"type": "SPIKE", "x": 569, "y": 0},
                             {"type": "SPIKE", "x": 570, "y": 0},
                             {"type": "SPIKE", "x": 571, "y": 0},
                             {"type": "SPIKE", "x": 572, "y": 0},
                             {"type": "SPIKE", "x": 573, "y": 0},
                             {"type": "SPIKE", "x": 574, "y": 0},
                             {"type": "SPIKE", "x": 575, "y": 0},
                             {"type": "SPIKE", "x": 576, "y": 0},
                             {"type": "SPIKE", "x": 577, "y": 0},
                             {"type": "SPIKE", "x": 578, "y": 0},
                             {"type": "SPIKE", "x": 579, "y": 0},
                             {"type": "SPIKE", "x": 580, "y": 0},
                             {"type": "SPIKE", "x": 581, "y": 0},
                             {"type": "SPIKE", "x": 582, "y": 0},
                             {"type": "SPIKE", "x": 583, "y": 0},
                             {"type": "SPIKE", "x": 584, "y": 0},
                             {"type": "SPIKE", "x": 585, "y": 0},
                             {"type": "SPIKE", "x": 586, "y": 0},
                             {"type": "SPIKE", "x": 587, "y": 0},
                             {"type": "SPIKE", "x": 588, "y": 0},
                             {"type": "SPIKE", "x": 589, "y": 0},
                             {"type": "SPIKE", "x": 590, "y": 0},
                             {"type": "SPIKE", "x": 591, "y": 0},
                             {"type": "SPIKE", "x": 592, "y": 0},
                             {"type": "SPIKE", "x": 593, "y": 0},
                             {"type": "SPIKE", "x": 594, "y": 0},
                             {"type": "SPIKE", "x": 595, "y": 0},
                             {"type": "SPIKE", "x": 596, "y": 0},
                             {"type": "SPIKE", "x": 597, "y": 0},
                             {"type": "SPIKE", "x": 598, "y": 0},
                             {"type": "SPIKE", "x": 599, "y": 0},
                             {"type": "SPIKE", "x": 600, "y": 0},
                             {"type": "SPIKE", "x": 601, "y": 0},
                             {"type": "SPIKE", "x": 602, "y": 0},
                             {"type": "SPIKE", "x": 603, "y": 0},
                             {"type": "SPIKE", "x": 604, "y": 0},
                             {"type": "SPIKE", "x": 605, "y": 0},
                             {"type": "SPIKE", "x": 606, "y": 0},
                             {"type": "SPIKE", "x": 607, "y": 0},
                             {"type": "SPIKE", "x": 608, "y": 0},
                             {"type": "SPIKE", "x": 609, "y": 0},
                             {"type": "SPIKE", "x": 610, "y": 0},
                             {"type": "SPIKE", "x": 611, "y": 0},
                             {"type": "SPIKE", "x": 612, "y": 0},
                             {"type": "SPIKE", "x": 613, "y": 0},
                             {"type": "SPIKE", "x": 614, "y": 0},
                             {"type": "SPIKE", "x": 615, "y": 0},
                             {"type": "SPIKE", "x": 616, "y": 0},
                             {"type": "SPIKE", "x": 617, "y": 0},
                             {"type": "SPIKE", "x": 618, "y": 0},
                             {"type": "SPIKE", "x": 619, "y": 0},
                             {"type": "SPIKE", "x": 620, "y": 0},
                             {"type": "SPIKE", "x": 621, "y": 0},
                             {"type": "SPIKE", "x": 622, "y": 0},
                             {"type": "SPIKE", "x": 623, "y": 0},
                             {"type": "SPIKE", "x": 624, "y": 0},
                             {"type": "SPIKE", "x": 625, "y": 0},
                             {"type": "SPIKE", "x": 626, "y": 0},
                             {"type": "SPIKE", "x": 627, "y": 0},
                             {"type": "SPIKE", "x": 628, "y": 0},
                             {"type": "SPIKE", "x": 629, "y": 0},
                             {"type": "SPIKE", "x": 630, "y": 0},
                             {"type": "SPIKE", "x": 631, "y": 0},
                             {"type": "SPIKE", "x": 632, "y": 0},
                             {"type": "SPIKE", "x": 633, "y": 0},
                             {"type": "SPIKE", "x": 634, "y": 0},
                             {"type": "SPIKE", "x": 635, "y": 0},
                             {"type": "SPIKE", "x": 636, "y": 0},
                             {"type": "SPIKE", "x": 637, "y": 0},
                             {"type": "SPIKE", "x": 638, "y": 0},
                             {"type": "SPIKE", "x": 639, "y": 0},
                             {"type": "SPIKE", "x": 640, "y": 0},
                             {"type": "SPIKE", "x": 641, "y": 0},
                             {"type": "SPIKE", "x": 642, "y": 0},
                             {"type": "SPIKE", "x": 643, "y": 0},
                             {"type": "SPIKE", "x": 644, "y": 0},
                             {"type": "SPIKE", "x": 645, "y": 0},
                             {"type": "SPIKE", "x": 646, "y": 0},
                             {"type": "SPIKE", "x": 647, "y": 0},
                             {"type": "SPIKE", "x": 648, "y": 0},
                             {"type": "SPIKE", "x": 649, "y": 0},
                             {"type": "SPIKE", "x": 650, "y": 0},
                             {"type": "SPIKE", "x": 651, "y": 0},
                             {"type": "SPIKE", "x": 652, "y": 0},
                             {"type": "SPIKE", "x": 653, "y": 0},
                             {"type": "SPIKE", "x": 654, "y": 0},
                             {"type": "SPIKE", "x": 655, "y": 0},
                             {"type": "SPIKE", "x": 656, "y": 0},
                             {"type": "SPIKE", "x": 657, "y": 0},
                             {"type": "SPIKE", "x": 658, "y": 0},
                             {"type": "SPIKE", "x": 659, "y": 0},
                             {"type": "SPIKE", "x": 660, "y": 0},
                             {"type": "SPIKE", "x": 661, "y": 0},
                             {"type": "SPIKE", "x": 662, "y": 0},
                             {"type": "SPIKE", "x": 663, "y": 0},
                             {"type": "SPIKE", "x": 664, "y": 0},
                             {"type": "SPIKE", "x": 665, "y": 0},
                             {"type": "SPIKE", "x": 666, "y": 0},
                             {"type": "SPIKE", "x": 667, "y": 0},
                             {"type": "SPIKE", "x": 668, "y": 0},
                             {"type": "SPIKE", "x": 669, "y": 0},
                             {"type": "SPIKE", "x": 670, "y": 0},
                             {"type": "SPIKE", "x": 671, "y": 0},
                             {"type": "SPIKE", "x": 672, "y": 0},
                             {"type": "SPIKE", "x": 673, "y": 0},
                             {"type": "SPIKE", "x": 674, "y": 0},
                             {"type": "SPIKE", "x": 675, "y": 0},
                             {"type": "SPIKE", "x": 676, "y": 0},
                             {"type": "SPIKE", "x": 677, "y": 0},
                             {"type": "SPIKE", "x": 678, "y": 0},
                             {"type": "SPIKE", "x": 679, "y": 0},
                             {"type": "SPIKE", "x": 680, "y": 0},
                             {"type": "SPIKE", "x": 681, "y": 0},
                             {"type": "SPIKE", "x": 682, "y": 0},
                             {"type": "SPIKE", "x": 683, "y": 0},
                             {"type": "SPIKE", "x": 684, "y": 0},
                             {"type": "SPIKE", "x": 685, "y": 0},
                             {"type": "SPIKE", "x": 686, "y": 0},
                             {"type": "SPIKE", "x": 687, "y": 0},
                             {"type": "SPIKE", "x": 688, "y": 0},
                             {"type": "SPIKE", "x": 689, "y": 0},
                             {"type": "SPIKE", "x": 690, "y": 0},
                             {"type": "SPIKE", "x": 691, "y": 0},
                             {"type": "SPIKE", "x": 692, "y": 0},
                             {"type": "SPIKE", "x": 693, "y": 0},
                             {"type": "SPIKE", "x": 694, "y": 0},
                             {"type": "SPIKE", "x": 695, "y": 0},
                             {"type": "SPIKE", "x": 696, "y": 0},
                             {"type": "SPIKE", "x": 697, "y": 0},
                             {"type": "SPIKE", "x": 698, "y": 0},
                             {"type": "SPIKE", "x": 699, "y": 0},
                             {"type": "SPIKE", "x": 700, "y": 0},
    
                             {"type": "BLOCK", "x": 490, "y": 3},
                             {"type": "BLOCK", "x": 500, "y": 2},
                             {"type": "BLOCK", "x": 510, "y": 5},
                             {"type": "BLOCK", "x": 520, "y": 4},
                             {"type": "BLOCK", "x": 530, "y": 3},
                             {"type": "BLOCK", "x": 540, "y": 2},
                             {"type": "BLOCK", "x": 550, "y": 4},
                             {"type": "BLOCK", "x": 560, "y": 5},
                             {"type": "BLOCK", "x": 570, "y": 2},
                             {"type": "BLOCK", "x": 580, "y": 3},
                             {"type": "BLOCK", "x": 590, "y": 4},
                             {"type": "BLOCK", "x": 600, "y": 3},
                             {"type": "BLOCK", "x": 610, "y": 5},
                             {"type": "BLOCK", "x": 620, "y": 2},
                             {"type": "BLOCK", "x": 630, "y": 4},
                             {"type": "BLOCK", "x": 640, "y": 4},
                             {"type": "BLOCK", "x": 650, "y": 2},
                             {"type": "BLOCK", "x": 660, "y": 5},
                             {"type": "BLOCK", "x": 670, "y": 3},
                             {"type": "BLOCK", "x": 680, "y": 3},
                             {"type": "BLOCK", "x": 690, "y": 5},
                             {"type": "BLOCK", "x": 700, "y": 2},
                             
                             {"type": "COIN",  "x": 650, "y": 4},
    
    
    
    
    
    
    
    
                             {"type": "GOAL", "x": 750, "y": 1}
                         ]
                        """);
                l1.setStars(1); // Easy
                l1.setAudioTrackId(1001);
                repository.save(l1);

                Level l2 = repository.findByLevelName("Back on Track").orElse(new Level());
                l2.setLevelName("Back on Track");
                l2.setLevelData("""
                            [
                        {"type": "BLOCK", "x": 10, "y": 0},
                        {"type": "BLOCK", "x": 11, "y": 0},
                        {"type": "SPIKE", "x": 15, "y": 0},
                        {"type": "BLOCK", "x": 20, "y": 1},
                        {"type": "SPIKE", "x": 25, "y": 0},
                        {"type": "COIN",  "x": 30, "y": 2},
                        {"type": "SPIKE", "x": 40, "y": 0},
                        {"type": "SPIKE", "x": 41, "y": 0},
                        {"type": "SPIKE", "x": 42, "y": 0},
                        {"type": "SPIKE", "x": 47, "y": 0},
                        {"type": "PORTAL_SHIP", "x": 40, "y": 2},
                        {"type": "SPIKE", "x": 47, "y": 0},
                        {"type": "SPIKE", "x": 48, "y": 0},
                        {"type": "SPIKE", "x": 49, "y": 0},
                        {"type": "SPIKE", "x": 50, "y": 0},
                        {"type": "PORTAL_BALL", "x": 51, "y": 3},
                        {"type": "BLOCK", "x": 70, "y": 5},
                        {"type": "BLOCK", "x": 71, "y": 5},
                        {"type": "BLOCK", "x": 72, "y": 5},
                        {"type": "BLOCK", "x": 73, "y": 5},
                        {"type": "BLOCK", "x": 74, "y": 5},
                        {"type": "PORTAL_UFO", "x": 80, "y": 3},
                        {"type": "BLOCK", "x": 90, "y": 0},
                        {"type": "BLOCK", "x": 90, "y": 1},
                        {"type": "BLOCK", "x": 90, "y": 2},
                        {"type": "BLOCK", "x": 90, "y": 3},
                        {"type": "SPIKE", "x": 90, "y": 4},
                        {"type": "PORTAL_WAVE", "x": 120, "y": 3},
                        {"type": "BLOCK", "x": 135, "y": 0},
                        {"type": "BLOCK", "x": 135, "y": 1},
                        {"type": "BLOCK", "x": 135, "y": 2},
                        {"type": "BLOCK", "x": 135, "y": 3},
                        {"type": "SPIKE", "x": 135, "y": 4},
                        {"type": "BLOCK", "x": 140, "y": 0},
                        {"type": "BLOCK", "x": 141, "y": 1},
                        {"type": "BLOCK", "x": 142, "y": 2},
                        {"type": "BLOCK", "x": 143, "y": 3},
                        {"type": "SPIKE", "x": 144, "y": 4},
                        {"type": "PORTAL_ROBOT", "x": 150, "y": 3},
                        {"type": "BLOCK", "x": 161, "y": 1},
                        {"type": "BLOCK", "x": 162, "y": 1},
                        {"type": "BLOCK", "x": 163, "y": 1},
                        {"type": "SPIKE", "x": 164, "y": 2},
                        {"type": "PORTAL_SPIDER", "x": 200, "y": 0},
                        {"type": "BLOCK", "x": 161, "y": 1},
                        {"type": "BLOCK", "x": 162, "y": 1},
                        {"type": "BLOCK", "x": 163, "y": 1},
                        {"type": "SPIKE", "x": 164, "y": 2},
                        {"type": "GOAL",  "x": 250, "y": 0}
                    ]
                        """);
                l2.setStars(2); // Normal
                l2.setAudioTrackId(102);
                repository.save(l2);

                Level l3 = repository.findByLevelName("Ship Challenge").orElse(new Level());
                l3.setLevelName("Ship Challenge");
                l3.setLevelData("""
                            [
                                {"type": "PORTAL_SHIP", "x": 5, "y": 1},
                                
                                {"type": "SPIKE", "x": 15, "y": 0},
                                {"type": "SPIKE_UPSIDE", "x": 15, "y": 5},
                                {"type": "BLOCK", "x": 15, "y": 6},
                                
                                {"type": "SPIKE", "x": 20, "y": 0},
                                {"type": "SPIKE_UPSIDE", "x": 20, "y": 6},
                                
                                {"type": "SPIKE", "x": 25, "y": 0},
                                {"type": "SPIKE_UPSIDE", "x": 25, "y": 6},
                                
                                {"type": "SPIKE", "x": 30, "y": 0},
                                {"type": "SPIKE_UPSIDE", "x": 30, "y": 6},
                                
                                {"type": "GOAL", "x": 40, "y": 3}
                            ]
                        """);
                l3.setStars(3); // Harder
                l3.setAudioTrackId(1001);
                repository.save(l3);

                System.out.println("Dummy levels created!");
            }
        };
    }
}